### ISSUE TITLE
Please support write operations

### ISSUE THREAD

**Issue by kof02guy** [prestodb/presto-go-client#28]
We use Query() for the write operations, of which the result could be empty.
It is wired that we use other libs like thrift to do write operations of presto.
I think many users need this feature. So that we can use this lib just as we do by database/sql

**Comment by fiorix** [comment]
The main reason we don't support write operations in this driver is because that's not how we write data to our warehouse at Facebook. I believe none of us in the team have plans to implement write operations but we'd be happy to review code and guide you through the implementation.

That said, I will mark this as an enhancement and let it park here until we get a pull request.

**Comment by chancez** [comment]
FWIW, you can insert using this package, it's just the returned object isn't populated.

**Comment by fiorix** [comment]
No plans to add this for now. Happy to re-open the discussion in case there is a backing PR.
